name = "creator-toolkit"
compatibility_date = "2024-07-15"

[env.production]
name = "creator-toolkit"

# Pages configuration
pages_build_output_dir = "."

# Build configuration
[build]
command = "npm run build"
watch_dir = "."

# Environment variables
[vars]
NODE_ENV = "production"
NODE_VERSION = "18.19.0"

# Build environment settings
[build.environment]
NODE_VERSION = "18.19.0"
NPM_VERSION = "10"