name: Deploy to Multiple Platforms

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.19.0'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Run build
      run: npm run build
      
    - name: Test build output
      run: |
        if [ ! -f "index.html" ]; then
          echo "Error: index.html not found after build"
          exit 1
        fi
        echo "Build test passed"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          .
          !node_modules
          !.git
          !.github
        retention-days: 7

  deploy-netlify:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.19.0'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Build for Netlify
      run: npm run deploy:netlify
      
    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod --dir=.
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  deploy-cloudflare:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.19.0'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Build for Cloudflare
      run: npm run deploy:cloudflare
      
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: xiaolu-tool
        directory: .
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}